#configuration for the prefab cli
--- 
## This is used for tagging the docker repository
#-!!str IMAGE_REPO: !!str ps
#
### This is used for tagging the docker image
#-!!str SERVICE_NAME: !!str prefab-spring-boot
#
### This is used for exposing the service port
#-!!str SERVICE_PORT: !!int 8080
#
### This is used for exposing the monitor port
#-!!str MONITOR_PORT: !!int 8081
